### PR TITLE
fix error: count(): Parameter must be an array or an object that implements Countable when use php 7.2

### PR DESCRIPTION
**Pull request by Mehrdad-Dadkhah**
Hi

In php 7.2, can not use count() function for string, null , .... 
and now parser have error: count(): Parameter must be an array or an object that implements Countable
at file: php-html-parser/src/PHPHtmlParser/Selector.php line 171

I just fix it.

### CODE REVIEW

**Comment by DanAlipes** [comment]
is this branch ready to be merged in. I would like to use this package with php 7.2

**Comment by alcaeus** [comment]
A fix has been merged in #126 but not released as a tag. This library hasn't seen a lot of activity/support for a while. In the meantime, I'm providing a fork that will work with PHP 7.2, as explained [here](https://github.com/paquettg/php-html-parser/pull/126#issuecomment-356625323).

**Comment by stzoran1** [comment]
You can fix this by ignoring this error, which can be done by adding next into your class which is using PHPHtmlParser:

`public function __construct()
   
 {
       
       if (version_compare(PHP_VERSION, '7.2.0', '>=')) {

            // Ignores notices and reports all other kinds... and warnings

            error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);

        }
 }
`

**Comment by alcaeus** [comment]
I explained that in the comment above your original comment: 

> [...] I'm providing a fork that will work with PHP 7.2, as explained [here](https://github.com/paquettg/php-html-parser/pull/126#issuecomment-356625323).

**Comment by paquettg** [comment]
This has been fixed in 2.0.0

**Pull request closed without merging**
